# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mcrow_full_ratio <- function(Wi, Wi_no_base, Yi, Yi_star, eYi, sigma_inverse) {
    .Call('_DivNet_mcrow_full_ratio', PACKAGE = 'DivNet', Wi, Wi_no_base, Yi, Yi_star, eYi, sigma_inverse)
}

mcrow_MCrow <- function(Yi, Wi, eYi, base, sigInv, MCiter, stepsize) {
    .Call('_DivNet_mcrow_MCrow', PACKAGE = 'DivNet', Yi, Wi, eYi, base, sigInv, MCiter, stepsize)
}

