# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigen_MCrow <- function(Yi, Wi, eYi, Q, base, sigInv, MCiter, stepsize) {
    .Call('_DivNet_eigen_MCrow', PACKAGE = 'DivNet', Yi, Wi, eYi, Q, base, sigInv, MCiter, stepsize)
}

