# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' MCrow
#'
#' This function simulates MC step for a single row.
#'
#' @author Ryan Moore
#'
#' @param Yi row of logratio matrix
#' @param Wi corresponding row of count matrix
#' @param eYi current expected value of logratio matrix
#' @param base OTU index used for base (1-based index)
#' @param sigInv current estimate of sigma inverse
#' @param MCiter number of MC samples to generate
#' @param stepsize variance used for MH samples. Tweak to adjust acceptance ratio
mcrow_MCrow <- function(Yi, Wi, eYi, base, sigInv, MCiter, stepsize) {
    .Call('_DivNet_mcrow_MCrow', PACKAGE = 'DivNet', Yi, Wi, eYi, base, sigInv, MCiter, stepsize)
}

